services:
  app:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev

    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/barbershopapi:z
    depends_on:
      - db
    networks:
      - barber-shop-net
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: barber-shop-api
      POSTGRES_PASSWORD: barber-shop-api
      POSTGRES_DB: barber-shop-api
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "5432:5432"
    networks:
      - barber-shop-net
networks:
  barber-shop-net:
    driver: bridge
volumes:
  db:

